backend:
  name: git-gateway
  branch: main

media_folder: "public/src/assets/blog"
public_folder: "/src/assets"

collections:
  - name: "posts"
    label: "Blog"
    folder: "blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "article.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }